### PR TITLE
fix(oxygen): update Ant scenarios to support Oxygen 22.0

### PR DESCRIPTION
**Pull request by AirQuick**
The Ant scenarios in `xspec.framework` do not work on Oxygen 22:
```console
...
BUILD FAILED
...\xspec\build.xml:366: The following error occurred while executing this line:
...\xspec\build.xml:178: java.lang.NoClassDefFoundError: org/apache/log4j/Logger
```

This pull request fixes it by copying the Ant scenario library configuration from Oxygen 22.0 build 2020021016.
Regarding the backward compatibility, I tested the updated Ant scenarios shortly on 21.1 and 19.0.

### CODE REVIEW

**Comment by AirQuick** [comment]
* I compared `<field name="extensionURLs">` (two instances) in this branch with the one in Oxygen 22.0. No difference.
* I tested the framework on Oxygen 22.0 (again) and 20.1 (new). The Ant scenarios (XSLT, XQuery, Schematron, XSLT code coverage, XSLT schema-aware, XQuery schema-aware) worked.

Merging this.
